name: Generate Snake Animation

on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Contribution Snake
    runs-on: ubuntu-latest

    steps:
      # ✅ Generate Snake SVG
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: abdurFaiz
          svg_out_path: dist/github-contribution-grid-snake.svg

      # ✅ Push to output branch
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
